---
title: "lab 7"
author: "divyank_19bce1354"
date: "11/04/2022"
output: html_document
---

```{r setup, include=FALSE}
```
```{r}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
#install.packages("factoextra")
#install.packages("cluster")
library(factoextra)
library(cluster)
#**************#**************
```
```{r}

#Load and preparing the data
df=read.csv("seeds_K Means.csv")
df <- na.omit(df)
head(df) 
df <- scale(df) # scale to normalize the values >>>> x-xbar/SD
head(df)
```
```{r}
#********************
#Determine the optimal no.of clusters=K
#********************

#plot number of clusters vs. total within sum of squares (Elbow method) 
fviz_nbclust(df, pam, method = "wss") # pam- partitioning around medians
```
```{r}
#***********************
#PERFORM K-MEANS CLUSTERING WITH OPTIMAL K
#***********************

#make this example reproducible
#randomly generated seed to determine the starting centroids of the clusters.
set.seed(1) 

#perform k-means clustering with k = 4 clusters
km <- pam(df, k=4)

#view results
km
```
```{r}
#plot results of final k-means model
fviz_cluster(km, data = df)

#add cluster assigment to original data
final_data <- cbind(df, cluster = km$cluster)

#view final data
head(final_data)
```