---
title: "lab 6"
author: "divyank_19bce1354"
date: "11/04/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
rm(list=ls())
#install.packages("factoextra")
#install.packages("cluster")
library(factoextra)
library(cluster)
```
```{r}
#**************
#Load and preparing the data
#**************

df <- read.csv("seeds_K Means.csv")
df <- na.omit(df)
head(df) 

df <- scale(df) # scale = (0 to 1) >>>> x-xbar/SD
head(df)
```
```{r}
#********************
#Determine the optimal no.of clusters=K
#********************

#plot number of clusters vs. total within sum of squares (Elbow method) 
fviz_nbclust(df, kmeans, method = "wss")
```
```{r}
#***********************
#PERFORM K-MEANS CLUSTERING WITH OPTIMAL K
#***********************

#make this example reproducible
#randomly generated seed to determine the starting centroids of the clusters.
set.seed(1) 
```
````{r}
#perform k-means clustering with k = 4 clusters
km <- kmeans(df, centers = 4, nstart = 25)

#view results
km
```
```{r}
#plot results of final k-means model
fviz_cluster(km, data = df)
```
```{r}
#add cluster assigment to original data
final_data <- cbind(read.csv("seeds_K Means.csv"), cluster = km$cluster)
#view final data
head(final_data)
```
